apps/login/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'^register$', views.register, name = 'register'),
    url(r'^login$', views.login, name = 'logging'),
    url(r'^success$', views.success, name = 'success'),
    url(r'^logout$', views.logout, name = 'logout')
]

apps/trips/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'^showaddpage$', views.showaddpage, name = 'showaddpage'),
    url(r'^add$', views.add, name = 'add')
#     url(r'^success$', views.success, name = 'success'),
#     url(r'^logout$', views.logout, name = 'logout')
]

black_belt/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', include('apps.login.urls', namespace ="login")),
    url(r'^trips/', include('apps.trips.urls', namespace ="trips")),

]

apps/login/models.py
from __future__ import unicode_literals
from django.db import models
import re, bcrypt

# NAME_REGEX = re.compile(r'^[A-Za-z]')
EMAIL_REGEX= re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')
# Create your models here.



class UserManager(models.Manager):
    def validate_inputs(self, params):
        errors=[]
#Dont pass the request object around


        user = User.objects.filter(u_name=params['u_name'])
        if user:
            errors.append("Username already exist")

        if len(params['f_name']) < 3 or len(params['u_name']) < 3:
            errors.append("Name and Username should be atleast 3 characters")

        # if not re.match(NAME_REGEX, params['f_name']) or re.match(NAME_REGEX, params['l_name']):
        #     errors.append("Name should have letters only")

        if len(params['password']) < 8:
            errors.append("Password should be longer than 8 characters")

        if not str(params['password'])== str(params['cpassword']):
            errors.append("passwords do not match")

        return errors

    def reg_valid(self, params):
        errors = self.validate_inputs(params)
        if len(errors) > 0:
            return (False, errors)

        pw_hash = bcrypt.hashpw(params['password'].encode(), bcrypt.gensalt())
        user = self.create(f_name = params['f_name'], pw_hash = pw_hash, u_name = params['u_name'])
        return (True, user)

    def login_valid(self, params):
        print params['password']
        user = User.objects.filter(u_name = params['u_name'])

        if user:
            if bcrypt.hashpw(params['password'].encode(), user[0].pw_hash.encode()) == user[0].pw_hash.encode():
                print bcrypt.hashpw(params['password'].encode(), user[0].pw_hash.encode())
                print bcrypt.hashpw(params['password'].encode(), bcrypt.gensalt())

                return (True, user[0])
            else:
                return (False, ["Username/password inside do not exist"])
        else:
            return (False, ["Username/password do not exist"])

# * will unpack a list and ** will unpack a dictionary

class User(models.Model):
    f_name = models.CharField(max_length=255) #unique =True(model validations)
    u_name = models.CharField(max_length=255)
    pw_hash = models.CharField(max_length=255)
    cpassword= models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    objects = UserManager()

apps/trips/models.py
from __future__ import unicode_literals
from ..login.models import User
from django.db import models
import re, bcrypt
import datetime

# Create your models here.
class TripManager(models.Manager):

    def valid_inputs(self, param):
        errors=[]

        if len(param['d_name']) < 0 or len(param['descrip']) < 0:
            errors.append("Destination,Description and Date fields cannot be blank")

        # if  param['f_date'] <= datetime.date.today() or  param['t_date'] <= datetime.date.today():
        #     errors.append("Dates cannot be in the past or today!")

        # if param['f_date']< param['t_date']:
        #     errors.append("Travel date to should not be before TravelDate From")

        return errors

    def valid_add(self, param):
        errors = self.valid_inputs(param)
        if len(errors) > 0:
            return (False, errors)
        trip = self.create(d_name = param['d_name'], descrip= param['descrip'], f_date = param['f_date'],t_date = param['t_date'])
        return (True, trip)

class Trip(models.Model):
    d_name = models.CharField(max_length=255) #unique =True(model validations)
    descrip = models.CharField(max_length=255)
    f_date= models.DateField(blank=True, null=True)
    t_date= models.DateField(blank=True, null=True)

    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    objects = TripManager()

apps/login/views.py
from django.shortcuts import render, redirect, HttpResponse
from .models import User
from django.contrib import messages
# Create your views here
def index(request):
    return render(request, 'login/index.html')

def register(request):
        if request.method == 'POST':
            params ={
                'f_name' : request.POST['f_name'],
                'u_name' : request.POST['u_name'],
                'password' : request.POST['password'],
                'cpassword' : request.POST['cpassword']
            }

            result = User.objects.reg_valid(params)
            if result[0] == False:
                print_messages(request, result[1])
                return redirect('login:index')

            return login_success(request, result[1])

def login(request):    
    if request.method == 'POST':
        params ={
        'u_name' : request.POST['u_name'],
        'password' : request.POST['password']
        }
        result = User.objects.login_valid(params)
        if result[0] == False:
            print_messages(request, result[1])
            return redirect('login:index')
        return login_success(request, result[1])
            #load our succesful login page

def login_success(request, user):

    request.session['user'] = {
        'id' : user.id,
        'f_name' : user.f_name,
        'u_name' : user.u_name,
    }
    return redirect ('trips:index')

def print_messages(request, message_list):
    for message in message_list:
        print message
        messages.add_message(request, messages.INFO, message)

def success(request):
    if not 'user' in request.session:
        return redirect('login:index')
    return render(request, 'login/success.html')

def logout(request):
    request.session.pop('user')
    return redirect('login:index')

apps/trips/views.py
from django.shortcuts import render, redirect, HttpResponse
from ..login.models import User
from ..trips.models import Trip
from django.contrib import messages

def index(request):
    context= {
    'trips' : Trip.objects.all()
    }
    return render(request, 'trips/trip.html')

def showaddpage(request):
    return render(request, 'trips/add.html')

def add(request):
    if request.method == 'POST':
        param ={
        'd_name' : request.POST['d_name'],
        'descrip': request.POST['descrip'],
        'f_date': request.POST['f_date'],
        't_date': request.POST['t_date']
        }
        result = Trip.objects.valid_add(param)
        print "Trip table is there"
        if result[0] == False:
            print_messages(request, result[1])
            return render(request, 'trips/add.html')

        return redirect('trips:index')
    return redirect('trips:index')

apps/login/templates/login/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Login And Registration</title>
  {% load staticfiles %}
  <link rel="stylesheet" href="{% static '/login/css/login.css' %}" media="screen" title="no title">
</head>
<body>
  {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
  <form action="{% url 'login:register' %}" method="post">

    {% csrf_token %}
    <h2>Registration</h2>
    <ul>
      <li>Name:<input type="text" name="f_name" value="" placeholder="eg.Sheldon"></li>
      <li>UserName:<input type="text" name="u_name" value="" placeholder="eg.Shel"></li>
      <li>Password:<input type="password" name="password" value="" placeholder="******"></li>
      <li>Confirm PW:<input type="password" name="cpassword" value="" placeholder="******"></li>
      <li><input type="submit" name="name" value="Register"></li>
    </ul>
  </form>

<hr>

  <form class="" action="{% url 'login:logging' %}" method="post">
    {% csrf_token %}
    <h2>Login</h2>
    <ul>
        <li>Username:<input type="text" name="u_name" value="" placeholder="Shel"></li>
        <li>Password:<input type="password" name="password" value="" placeholder="*********"></li>
        <li><input type="submit" name="name" value="Login"></li>
    </ul>
  </form>

</body>
</html>

apps/login/templates/login/success.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Document</title>
</head>
<body>
  <h1>Hello,{{request.session.user.u_name}}</h1>
  <h3>Succesfully registered! Please login to go to the dashboard</h3>
  <form action="{% url 'login:logout' %}" value="Log Out">
    <input type="submit" name="name" value="Log Out">
  </form>
</body>
</html>

apps/trips/templates/trips/add.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  {% load staticfiles %}
  <link rel="stylesheet" href="{% static '/trips/css/trips.css' %}" media="screen" title="no title">
  <title>Add a Trip</title>
</head>
<body>
<a href="{% url 'trips:index' %}">Home</a>
<a href="{% url 'login:logout' %}">Logout</a>

  <form action="{% url 'trips:add' %}" method="post">

      {% csrf_token %}
      <h2>Add a Trip</h2>
      <ul>
        <li>Destination:<input type="text" name="d_name" value="" placeholder="eg.London"></li>
        <li>Description:<input type="text" name="descrip" value="" placeholder="eg.visit Eiffel"></li>
        <li>Travel Date From:<input type="date" name="f_date" value="" placeholder="yyyy-mm-dd"></li>
        <li>Travel Date To:<input type="date" name="t_date" value="" placeholder="yyyy-mm-dd"></li>
        <li><input type="submit" name="name" value="Add"></li>
      </ul>
  </form>


  {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}


</body>
</html>

apps/trips/templates/trips/trip.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Document</title>
</head>
<body>
  <h1>Hello,{{request.session.user.u_name}}</h1>
  <h3>Your Trip Schedules</h3>

  <table>
    <thead>
      <tr>
        <td> Destination </td>
        <td> Travel Start Date </td>
        <td> Travel End Date </td>
        <td> Plan </td>
      </tr>
    </thead>

    <tbody>
      {% for trip in trips %}
      <tr>
        <td> {{trip.d_name}}</td>
        <td> {{trip.f_date}} </td>
        <td> {{trip.t_date}}</td>
        <td> {{trip.descrip}}</td>
      </tr>
      {% endfor %}
    </tbody>
</table>

<h3>Other User's Travel Plans</h3>
<table>
<thead>
  <tr>
    <td> Name </td>
    <td> Destination </td>
    <td> Travel Start Date </td>
    <td> Travel End Date </td>
    <td> Do you want to Join? </td>
  </tr>
</thead>


</table>

<a href="{% url 'login:logout' %}">Logout</a>

<a href="{% url 'trips:showaddpage' %}">Add Travel Plan</a>


</body>
</html>